# version: "2"
# services:
#   node:
#     image: "node:8"
#     user: "node"
#     environment:
#       - NODE_ENV=production
#     ports:
#       - "4200:4200"
#     volumes:
#       - ./:/home/node/app
#     expose:
#       - "8081"
#     command: "npm start"